# Generated by Django 2.2.5 on 2019-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chickenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chikenkind',
            name='show',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chikenkind',
            name='text',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
